@startuml
hide circle
skinparam Shadowing false
skinparam class {
    backgroundColor GhostWhite
}


class user {
    (pk) id: Integer
    name: String
    username: String
    password: String
}

class purchase {
    (pk) id: Integer
    (fk) item_id: item
    amount: Integer
    collected: Boolean
}


class item {
    (pk) id: Integer
    (fk) kategoria_id: kategoria
    name: String
}

class category {
    (pk) id: Integer
    name: String
}

class list {
    (pk) id: Integer
    (fk) user_id: Integer
    name: String
    date: Date
    completed: Boolean
}

class listPurchase	{
    (fk) list_id: list
    (fk) item_id: item
}

item "*" -- "1" category
list "1" -- "*" user
list "1" -- "*" listPurchase
purchase "1" -- "*" listPurchase
item "*" -- "1" purchase

@endum
